### 12-1: Filtering Based on String

In [359]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [360]:
df.loc[df['City'].str.contains("New")] # Case sensitive

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [361]:
df.loc[df['City'].str.contains("new", case=False)] # Case insensitive

# We can also use regular expression

# Starts with Los
df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [362]:
df.loc[df['City'].str.contains(r"Los")]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [363]:
# Ends with rk

df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [364]:
# Name starts with a vowel

df.loc[df['Name'].str.contains(r"^[AEIOU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [365]:
# String contains New or Los

df.loc[df['City'].str.contains(r"New|Los")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000

### 12-2: Adding new Column and Saving the File

In [366]:
df = pd.read_csv("./student_data.csv")

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [367]:
# Adding a column with constant value

df['Country'] = 'Bangladesh'

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Country
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,Bangladesh
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Bangladesh
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,Bangladesh
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,Bangladesh
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Bangladesh
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,Bangladesh
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Bangladesh
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,Bangladesh
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,Bangladesh
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Bangladesh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,Bangladesh
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Bangladesh
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,Bangladesh
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Bangladesh
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,Bangladesh
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,Bangladesh
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Bangladesh
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,Bangladesh
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh

In [368]:
df['Total Marks'] = df['Data Structure Marks'] + df['Python Marks'] + df['Algorithm Marks']

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Country,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,Bangladesh,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Bangladesh,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,Bangladesh,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,Bangladesh,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Bangladesh,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,Bangladesh,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Bangladesh,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,Bangladesh,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,Bangladesh,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,Bangladesh,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Bangladesh,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,Bangladesh,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,Bangladesh,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Bangladesh,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,Bangladesh,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Bangladesh,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,Bangladesh,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,Bangladesh,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Bangladesh,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,Bangladesh,261.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN

In [369]:
import numpy as np

df['A+ in DS'] = np.where(df['Data Structure Marks'] > 90, 'A+', 'A-')

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Country,Total Marks,A+ in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,Bangladesh,258.0,A-
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,Bangladesh,261.0,A-
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,Bangladesh,238.0,A-
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Bangladesh,NaN,A-
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,Bangladesh,228.0,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Bangladesh,NaN,A-
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,Bangladesh,247.0,A-
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,Bangladesh,220.0,A-
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,Bangladesh,266.0,A-
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Bangladesh,NaN,A-
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,Bangladesh,257.0,A-
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,Bangladesh,229.0,A-
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Bangladesh,NaN,A-
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,Bangladesh,256.0,A-
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,Bangladesh,273.0,A-
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,Bangladesh,261.0,A-
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Bangladesh,NaN,A-
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,Bangladesh,261.0,A-
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A-

In [370]:
df['Passed in DS'] = np.where(df['Data Structure Marks'] > 70, True, False)

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Country,Total Marks,A+ in DS,Passed in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,Bangladesh,258.0,A-,True
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+,True
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,Bangladesh,261.0,A-,True
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,Bangladesh,238.0,A-,True
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Bangladesh,NaN,A-,False
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,Bangladesh,228.0,A-,True
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Bangladesh,NaN,A-,True
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,Bangladesh,247.0,A-,True
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,Bangladesh,220.0,A-,True
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,Bangladesh,266.0,A-,True
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Bangladesh,NaN,A-,False
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,Bangladesh,257.0,A-,True
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,Bangladesh,229.0,A-,True
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Bangladesh,NaN,A-,False
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,Bangladesh,256.0,A-,True
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+,True
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,Bangladesh,273.0,A-,True
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,Bangladesh,261.0,A-,True
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Bangladesh,NaN,A-,False
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,Bangladesh,261.0,A-,True
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A-,False

In [371]:
df['First Name'] = df['FullName'].str.split(' ').str[0]
df['Last Name'] = df['FullName'].str.split(' ').str[1]

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Country,Total Marks,A+ in DS,Passed in DS,First Name,Last Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,Bangladesh,258.0,A-,True,Alif,Rahman
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+,True,Fatima,Akhter
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,Bangladesh,261.0,A-,True,Imran,Hossain
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,Bangladesh,238.0,A-,True,Jannatul,Ferdous
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Bangladesh,NaN,A-,False,Kamal,Uddin
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,Bangladesh,228.0,A-,True,Laila,Begum
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Bangladesh,NaN,A-,True,Mahmudul,Hasan
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,Bangladesh,247.0,A-,True,Nadia,Islam
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,Bangladesh,220.0,A-,True,Omar,Faruq
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,Bangladesh,266.0,A-,True,Priya,Sharma
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Bangladesh,NaN,A-,False,Rahim,Sheikh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,Bangladesh,257.0,A-,True,Sadia,Chowdhury
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,Bangladesh,229.0,A-,True,Tanvir,Ahmed
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Bangladesh,NaN,A-,False,Urmi,Akter
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,Bangladesh,256.0,A-,True,Wahiduzzaman,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+,True,Ziaur,Rahman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,Bangladesh,273.0,A-,True,Afsana,Mimi
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,Bangladesh,261.0,A-,True,Babul,Ahmed
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Bangladesh,NaN,A-,False,Faria,Rahman
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,Bangladesh,261.0,A-,True,Nasir,Khan
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A-,False,NaN,NaN

In [372]:
df.to_html("new_data.html")
df.to_csv("new_data.csv")

df_1 = pd.read_csv("./new_data.csv")

df_1

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Country,Total Marks,A+ in DS,Passed in DS,First Name,Last Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,Bangladesh,258.0,A-,True,Alif,Rahman
1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+,True,Fatima,Akhter
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,Bangladesh,261.0,A-,True,Imran,Hossain
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,Bangladesh,238.0,A-,True,Jannatul,Ferdous
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Bangladesh,NaN,A-,False,Kamal,Uddin
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,Bangladesh,228.0,A-,True,Laila,Begum
6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Bangladesh,NaN,A-,True,Mahmudul,Hasan
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,Bangladesh,247.0,A-,True,Nadia,Islam
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,Bangladesh,220.0,A-,True,Omar,Faruq
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,Bangladesh,266.0,A-,True,Priya,Sharma
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Bangladesh,NaN,A-,False,Rahim,Sheikh
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,Bangladesh,257.0,A-,True,Sadia,Chowdhury
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,Bangladesh,229.0,A-,True,Tanvir,Ahmed
13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Bangladesh,NaN,A-,False,Urmi,Akter
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,Bangladesh,256.0,A-,True,Wahiduzzaman,NaN
15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Bangladesh,NaN,A+,True,Ziaur,Rahman
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,Bangladesh,273.0,A-,True,Afsana,Mimi
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,Bangladesh,261.0,A-,True,Babul,Ahmed
18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Bangladesh,NaN,A-,False,Faria,Rahman
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,Bangladesh,261.0,A-,True,Nasir,Khan
20,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A-,False,NaN,NaN

### 12-3: Checking Duplicates and Null Values in DF

In [373]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)

# Unique works on only Series or Column
# Not works on rows

df['Name'].unique()

len(df['Name'].unique())

4

In [374]:
df_1 = pd.read_csv("student_data.csv")

df_1['Data Structure Marks'].unique() # Will return NaN too
len(df_1['Data Structure Marks'].unique())

df_1['Data Structure Marks'].nunique() # Will not return NaN

12

In [375]:
# nunique() works on DataFrame as to see the unique values count

df.nunique()

Name     4
City     4
Score    5
dtype: int64

#### Check Null

In [376]:
df_1.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False,True
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False,True
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False,True
19,False,False,False,False,False,False,False,False,False,False
20,True,True,True,True,True,True,True,True,True,True

In [377]:
df_1['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20     True
Name: Data Structure Marks, dtype: bool

In [378]:
df_1['Data Structure Marks'].notnull() # Opposite of isnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20    False
Name: Data Structure Marks, dtype: bool

In [379]:
# To check if a Series or Column has a NaN Values

df_1['Data Structure Marks'].hasnans

True

In [380]:
df_1['StudentID'].hasnans

True

### 12-4: Handling Duplicates Values

In [381]:
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [382]:
df.duplicated().sum()

# Duplicated will return if values exactly matches from Columns

np.int64(1)

In [383]:
# Deleting duplicates values
# Permanent

df.drop_duplicates(inplace=True)

df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [384]:
# Duplicate Deletion on basis of Name

df.drop_duplicates(subset=['Name'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [385]:
# Duplicate Deletion on basis of Name, City meaning multiple

df.drop_duplicates(subset=['Name', 'City'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [386]:
# Duplicate Deletion on basis of Name, City meaning multiple
# Also keep last one and remove first one

df.drop_duplicates(subset=['Name', 'City'], keep="last")

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

### 12-5: Handling Null Values

In [387]:
df = pd.read_csv("student_data.csv")

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [388]:
# Drop null values row
# If it founds and null or NaN values in column or row it will delete the row
# Use inplace True to change the main df

df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11

In [389]:
# Delete that row which all column values are NaN only.

df.dropna(how='all', inplace=True)

In [390]:
# Deleting on basis of a Columns

df.dropna(subset=['Python Marks', 'Algorithm Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11

In [391]:
# Fill Null Values

df.fillna(0) # Fill with 0

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram,0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka,0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram,0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11

In [392]:
df['FullName'] = df['FullName'].fillna('Unknown')

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11

In [393]:
df = pd.read_csv("student_data.csv")

df['Python Marks'] = df['Python Marks'].fillna(df['Python Marks'].mean())

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,NaN

### 12-6: Statistical Functions in Pandas

In [394]:
# Total Sum of a numbered column

# Sum

df['Data Structure Marks'].sum()

np.float64(1344.0)

In [395]:
# Max and Min value

print(df['Data Structure Marks'].max())
print(df['Data Structure Marks'].min())

94.0
72.0

In [396]:
# Mean -> Average

df['Data Structure Marks'].mean()

np.float64(84.0)

In [397]:
# Median -> Moddok

df['Data Structure Marks'].median()

np.float64(85.5)

In [398]:
# Mode -> Highest Frequency Number

df['Data Structure Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [399]:
# Standard Deviation > Std

df['Data Structure Marks'].std()

np.float64(6.501281924871945)

In [400]:
# Correlation Matrix

print(df[['Data Structure Marks', 'Algorithm Marks']].corr())  # Perefectly Correlated that's why 1

print(df[['Data Structure Marks', 'Python Marks']].corr()) 

# If 0 then no correlations
# If 1 means positively correlated, if python marks increases then data sturcute marks will increase
# If -1 means negatively correlated, if python marks increases then data structue marks will lower

                      Data Structure Marks  Algorithm Marks
Data Structure Marks                   1.0              1.0
Algorithm Marks                        1.0              1.0
                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.776845
Python Marks                      0.776845      1.000000

In [401]:
# Sum in different columns

print(df[['Data Structure Marks', 'Python Marks']].sum())

Data Structure Marks    1344.0
Python Marks            1799.0
dtype: float64

In [402]:
# Sum in different columns row wise

print(df[['Data Structure Marks', 'Python Marks']].sum(axis=1))

0     173.000000
1     177.666667
2     173.000000
3     160.000000
4      95.000000
5     153.000000
6     165.666667
7     166.000000
8     148.000000
9     177.000000
10     91.000000
11    172.000000
12    154.000000
13     85.666667
14    170.000000
15    179.666667
16    183.000000
17    173.000000
18     85.666667
19    175.000000
20     85.666667
dtype: float64

In [403]:
# Easy way to sum multiple columns then create a new column

df['Total Marks'] = df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].sum()

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,NaN
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,NaN
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,NaN
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,NaN
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,NaN
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,NaN,NaN

In [404]:
# Best Way

df['Total Marks'] = df.iloc[::,2:5].sum(axis=1)

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,269.666667
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,245.666667
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,273.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.000000
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,NaN,85.666667

In [405]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             16.000000        16.000000     21.000000    21.000000
mean              84.000000        84.000000     85.666667   213.666667
std                6.501282         6.501282      4.512944    73.089215
min               72.000000        72.000000     76.000000    85.666667
25%               79.500000        79.500000     85.000000   220.000000
50%               85.500000        85.500000     85.666667   247.000000
75%               88.250000        88.250000     88.000000   261.000000
max               94.000000        94.000000     95.000000   273.666667

### 12-7: Apply Function in DF

In [406]:
# Min max Scaling

mn = df['Total Marks'].min()
mx = df['Total Marks'].max()

# Scaled = (x-min) / (mx-min)

df['Scaled Marks'] = df['Total Marks'].apply(lambda x: (x-mn)/(mx-mn))

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.000000,0.916667
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,269.666667,0.978723
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.000000,0.932624
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.000000,0.810284
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,95.000000,0.049645
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.000000,0.757092
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,245.666667,0.851064
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.000000,0.858156
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.000000,0.714539
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.000000,0.959220
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,91.000000,0.028369
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,257.000000,0.911348
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.000000,0.762411
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,85.666667,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.000000,0.906028
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,273.666667,1.000000
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,273.000000,0.996454
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.000000,0.932624
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN,85.666667,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.000000,0.932624
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,NaN,85.666667,0.000000

In [407]:
# Custom built function

def grading_system(marks):
    if marks >= 260:
        return "A+"
    elif marks >= 250:
        return "A"
    else:
        return "A-"
    
df['Grade'] = df['Total Marks'].apply(grading_system)

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.000000,0.916667,A
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,269.666667,0.978723,A+
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.000000,0.932624,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.000000,0.810284,A-
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,95.000000,0.049645,A-
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.000000,0.757092,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,245.666667,0.851064,A-
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.000000,0.858156,A-
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.000000,0.714539,A-
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.000000,0.959220,A+
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,91.000000,0.028369,A-
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,257.000000,0.911348,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.000000,0.762411,A-
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,85.666667,0.000000,A-
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.000000,0.906028,A
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,273.666667,1.000000,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,273.000000,0.996454,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.000000,0.932624,A+
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN,85.666667,0.000000,A-
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.000000,0.932624,A+
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,NaN,85.666667,0.000000,A-

In [408]:
def marking_system(df):
    a = df['Data Structure Marks'] * 3
    b = df['Python Marks'] * 3
    c = df['Algorithm Marks'] * 4

    return a + b + c

df['Exceptional Marks'] = df.apply(marking_system, axis=1) # Row wise that's why

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.000000,0.916667,A,859.0
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,269.666667,0.978723,A+,901.0
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.000000,0.932624,A+,871.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.000000,0.810284,A-,792.0
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,95.000000,0.049645,A-,NaN
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.000000,0.757092,A-,759.0
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,245.666667,0.851064,A-,817.0
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.000000,0.858156,A-,822.0
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.000000,0.714539,A-,732.0
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.000000,0.959220,A+,887.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,91.000000,0.028369,A-,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,257.000000,0.911348,A,856.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.000000,0.762411,A-,762.0
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,85.666667,0.000000,A-,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.000000,0.906028,A,854.0
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,273.666667,1.000000,A+,915.0
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,273.000000,0.996454,A+,909.0
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.000000,0.932624,A+,871.0
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN,85.666667,0.000000,A-,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.000000,0.932624,A+,869.0
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,NaN,85.666667,0.000000,A-,NaN

### 12-8: DateTime and Timedelta

In [409]:
df['EnrollmentDate']

0     2024-01-15
1     2024-01-20
2     2024-02-10
3     2024-02-12
4     2024-03-05
5     2024-03-08
6     2024-04-01
7     2024-04-22
8     2024-05-16
9     2024-05-20
10    2024-06-11
11    2024-06-14
12    2024-07-02
13    2024-07-09
14    2024-08-18
15    2024-08-21
16    2025-09-01
17    2025-09-05
18    2025-09-15
19    2025-10-02
20           NaN
Name: EnrollmentDate, dtype: str

In [410]:
# We are converting into Pandas Datetime64 so that we can work around with rows with timing conditions
# Otherwise we have to do manual splitting from str and then work

df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])

In [ ]:
# Creating new columns from that EnrollmentDate
df['Enrollment Year'] = df['EnrollmentDate'].dt.year

df['Enrollment Date'] = df['EnrollmentDate'].dt.day

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.000000,0.916667,A,859.0,2024.0,15.0
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,269.666667,0.978723,A+,901.0,2024.0,20.0
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.000000,0.932624,A+,871.0,2024.0,10.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.000000,0.810284,A-,792.0,2024.0,12.0
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,95.000000,0.049645,A-,NaN,2024.0,5.0
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.000000,0.757092,A-,759.0,2024.0,8.0
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,245.666667,0.851064,A-,817.0,2024.0,1.0
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.000000,0.858156,A-,822.0,2024.0,22.0
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.000000,0.714539,A-,732.0,2024.0,16.0
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.000000,0.959220,A+,887.0,2024.0,20.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,91.000000,0.028369,A-,NaN,2024.0,11.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,257.000000,0.911348,A,856.0,2024.0,14.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.000000,0.762411,A-,762.0,2024.0,2.0
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,85.666667,0.000000,A-,NaN,2024.0,9.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.000000,0.906028,A,854.0,2024.0,18.0
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,273.666667,1.000000,A+,915.0,2024.0,21.0
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,273.000000,0.996454,A+,909.0,2025.0,1.0
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.000000,0.932624,A+,871.0,2025.0,5.0
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,NaN,85.666667,0.000000,A-,NaN,2025.0,15.0
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.000000,0.932624,A+,869.0,2025.0,2.0
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaT,NaN,NaN,NaN,85.666667,0.000000,A-,NaN,NaN,NaN

In [420]:
# Time Delta

df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])

df['Total time taken to finish'] = df['FinishedDate'] - df['EnrollmentDate']

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.0,0.916667,A,859.0,2024.0,15.0,2024-03-23,68 days
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.0,0.932624,A+,871.0,2024.0,10.0,2024-05-01,81 days
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.0,0.810284,A-,792.0,2024.0,12.0,2024-04-10,58 days
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.0,0.757092,A-,759.0,2024.0,8.0,2024-04-21,44 days
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.0,0.858156,A-,822.0,2024.0,22.0,2024-07-03,72 days
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.0,0.714539,A-,732.0,2024.0,16.0,2024-06-22,37 days
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.0,0.959220,A+,887.0,2024.0,20.0,2024-07-09,50 days
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,257.0,0.911348,A,856.0,2024.0,14.0,2024-08-21,68 days
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.0,0.762411,A-,762.0,2024.0,2.0,2024-09-27,87 days
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.0,0.906028,A,854.0,2024.0,18.0,2024-10-05,48 days
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,273.0,0.996454,A+,909.0,2025.0,1.0,2025-10-23,52 days
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.0,0.932624,A+,871.0,2025.0,5.0,2025-10-15,40 days
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.0,0.932624,A+,869.0,2025.0,2.0,2025-11-11,40 days

### 12-9: Pandas Group By

In [421]:
import numpy as np

df.loc[df['FullName'] == 'Afsana Mimi', 'Total Marks'] = np.nan 
df.loc[df['FullName'] == 'Sadia Chowdhury', 'Total Marks'] = np.nan 
df.loc[df['FullName'] == 'Alif Rahman', 'Total Marks'] = np.nan

In [422]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,NaN,0.916667,A,859.0,2024.0,15.0,2024-03-23,68 days
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.0,0.932624,A+,871.0,2024.0,10.0,2024-05-01,81 days
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.0,0.810284,A-,792.0,2024.0,12.0,2024-04-10,58 days
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.0,0.757092,A-,759.0,2024.0,8.0,2024-04-21,44 days
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.0,0.858156,A-,822.0,2024.0,22.0,2024-07-03,72 days
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.0,0.714539,A-,732.0,2024.0,16.0,2024-06-22,37 days
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.0,0.959220,A+,887.0,2024.0,20.0,2024-07-09,50 days
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,NaN,0.911348,A,856.0,2024.0,14.0,2024-08-21,68 days
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.0,0.762411,A-,762.0,2024.0,2.0,2024-09-27,87 days
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.0,0.906028,A,854.0,2024.0,18.0,2024-10-05,48 days
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,NaN,0.996454,A+,909.0,2025.0,1.0,2025-10-23,52 days
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.0,0.932624,A+,871.0,2025.0,5.0,2025-10-15,40 days
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.0,0.932624,A+,869.0,2025.0,2.0,2025-11-11,40 days

In [423]:
instructor_group = df.groupby("Instructor")

instructor_group

In [ ]:
for instructor, df_ins in instructor_group: 
    display(instructor)
    display(df_ins)

'Mr. David'

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,220.0,0.714539,A-,732.0,2024.0,16.0,2024-06-22,37 days
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,229.0,0.762411,A-,762.0,2024.0,2.0,2024-09-27,87 days

'Mr. Karim'

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,NaN,0.916667,A,859.0,2024.0,15.0,2024-03-23,68 days
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,261.0,0.932624,A+,871.0,2024.0,10.0,2024-05-01,81 days
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,256.0,0.906028,A,854.0,2024.0,18.0,2024-10-05,48 days
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,NaN,0.996454,A+,909.0,2025.0,1.0,2025-10-23,52 days

'Ms. Salma'

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,238.0,0.810284,A-,792.0,2024.0,12.0,2024-04-10,58 days
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,228.0,0.757092,A-,759.0,2024.0,8.0,2024-04-21,44 days
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,247.0,0.858156,A-,822.0,2024.0,22.0,2024-07-03,72 days
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,266.0,0.959220,A+,887.0,2024.0,20.0,2024-07-09,50 days
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,NaN,0.911348,A,856.0,2024.0,14.0,2024-08-21,68 days
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,261.0,0.932624,A+,871.0,2025.0,5.0,2025-10-15,40 days
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,261.0,0.932624,A+,869.0,2025.0,2.0,2025-11-11,40 days

In [427]:
# Overall full DataFrame
# df.min()

# Under specific group: Instructor
instructor_group.min()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
Instructor,,,,,,,,,,,,,,,,,
Mr. David,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,2024-06-22,220.0,0.714539,A-,732.0,2024.0,2.0,2024-06-22,37 days
Mr. Karim,PH1001,Afsana Mimi,85.0,85.0,84.0,Completed,2024-01-15,Dhaka,2024-03-23,256.0,0.906028,A,854.0,2024.0,1.0,2024-03-23,48 days
Ms. Salma,PH1004,Babul Ahmed,75.0,75.0,78.0,Completed,2024-02-12,Chattogram,2024-04-10,228.0,0.757092,A,759.0,2024.0,2.0,2024-04-10,40 days

In [430]:
display(instructor_group.max())
display(instructor_group.describe())

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
Instructor,,,,,,,,,,,,,,,,,
Mr. David,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,2024-09-27,229.0,0.762411,A-,762.0,2024.0,16.0,2024-09-27,87 days
Mr. Karim,PH1017,Wahiduzzaman,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,2025-10-23,261.0,0.996454,A+,909.0,2025.0,18.0,2025-10-23,81 days
Ms. Salma,PH1020,Sadia Chowdhury,89.0,89.0,89.0,Completed,2025-10-02,Sylhet,2025-11-11,266.0,0.959220,A-,887.0,2025.0,22.0,2025-11-11,72 days

           Data Structure Marks                                             \
                          count       mean   min    25%   50%    75%   max
Instructor
Mr. David                   2.0  73.500000  72.0  72.75  73.5  74.25  75.0
Mr. Karim                   4.0  87.250000  85.0  85.75  87.0  88.50  90.0
Ms. Salma                   7.0  83.142857  75.0  79.50  85.0  87.00  89.0

                     Algorithm Marks             ...        FininshedDate  \
                 std           count       mean  ...                  max
Instructor                                       ...
Mr. David   2.121320             2.0  73.500000  ...  2024-09-27 00:00:00
Mr. Karim   2.217356             4.0  87.250000  ...  2025-10-23 00:00:00
Ms. Salma   5.273474             7.0  83.142857  ...  2025-11-11 00:00:00

                Total time taken to finish                           \
            std                      count                     mean
Instructor
Mr. David   NaN                          2         62 days 00:00:00
Mr. Karim   NaN                          4         62 days 06:00:00
Ms. Salma   NaN                          7  53 days 03:25:42.857142

                                                                  \
                         min               25%               50%
Instructor
Mr. David   37 days 00:00:00  49 days 12:00:00  62 days 00:00:00
Mr. Karim   48 days 00:00:00  51 days 00:00:00  60 days 00:00:00
Ms. Salma   40 days 00:00:00  42 days 00:00:00  50 days 00:00:00


                         75%               max                      std
Instructor
Mr. David   74 days 12:00:00  87 days 00:00:00  35 days 08:31:41.294725
Mr. Karim   71 days 06:00:00  81 days 00:00:00  15 days 04:42:09.426892
Ms. Salma   63 days 00:00:00  72 days 00:00:00  13 days 03:48:03.680442

[3 rows x 96 columns]

### 12-10: Group by Example

In [437]:
mean_marks = instructor_group['Total Marks'].mean()

In [440]:
df['Total Marks'] = df['Total Marks'].fillna(df['Instructor']).map(mean_marks)

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,FinishedDate,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrollment Year,Enrollment Date,FininshedDate,Total time taken to finish
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,2024-03-23,258.500000,0.916667,A,859.0,2024.0,15.0,2024-03-23,68 days
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,2024-05-01,NaN,0.932624,A+,871.0,2024.0,10.0,2024-05-01,81 days
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,2024-04-10,NaN,0.810284,A-,792.0,2024.0,12.0,2024-04-10,58 days
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,2024-04-21,NaN,0.757092,A-,759.0,2024.0,8.0,2024-04-21,44 days
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,2024-07-03,NaN,0.858156,A-,822.0,2024.0,22.0,2024-07-03,72 days
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,2024-06-22,NaN,0.714539,A-,732.0,2024.0,16.0,2024-06-22,37 days
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,2024-07-09,NaN,0.959220,A+,887.0,2024.0,20.0,2024-07-09,50 days
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,2024-08-21,250.166667,0.911348,A,856.0,2024.0,14.0,2024-08-21,68 days
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2024-09-27,NaN,0.762411,A-,762.0,2024.0,2.0,2024-09-27,87 days
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,2024-10-05,NaN,0.906028,A,854.0,2024.0,18.0,2024-10-05,48 days
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,2025-10-23,258.500000,0.996454,A+,909.0,2025.0,1.0,2025-10-23,52 days
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,2025-10-15,NaN,0.932624,A+,871.0,2025.0,5.0,2025-10-15,40 days
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2025-11-11,NaN,0.932624,A+,869.0,2025.0,2.0,2025-11-11,40 days