### Problem 1

In [36]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})
                   
print(df)  

# Replace null values based on given conditions
display(df.fillna({'A': 0.0, 'B': 99.0, 'C': 'Unknown'}))


# Forward fill column B
df2 = df.copy()
df2['B'] = df2['B'].ffill()
display(df2)


# Fills missing values in numeric columns with the mean of the column and in string columns with 'Unknown'.
df3 = df.copy()

num_cols = df3.select_dtypes(include=[np.number]).columns
df3[num_cols] = df3[num_cols].fillna(df3[num_cols].mean())

str_cols = df3.select_dtypes(include=['object', 'category']).columns
df3[str_cols] = df3[str_cols].fillna('Unknown')

df3

     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
2  NaN   NaN    c
3  4.0   NaN  NaN
4  5.0  10.0    e

     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  Unknown
4  5.0  10.0        e

     A     B    C
0  1.0   5.0    a
1  2.0   5.0    b
2  NaN   5.0    c
3  4.0   5.0  NaN
4  5.0  10.0    e

/tmp/ipykernel_104958/1076322649.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df3.select_dtypes(include=['object', 'category']).columns

     A     B        C
0  1.0   5.0        a
1  2.0   7.5        b
2  3.0   7.5        c
3  4.0   7.5  Unknown
4  5.0  10.0        e

### Problem 2

In [44]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})
                   
display(df)

# Drop rows where column A has missing values
display(df.dropna(subset=['A']))


# Drop rows with less than 2 non-null values
display(df.dropna(thresh=2))


# Drop rows where both Column A and Column B has missing values
display(df.dropna(subset=['A', 'B'], how='all'))

     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
2  NaN   NaN    c
3  4.0   NaN  NaN
4  5.0  10.0    e

     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
3  4.0   NaN  NaN
4  5.0  10.0    e

     A     B  C
0  1.0   5.0  a
1  2.0   NaN  b
4  5.0  10.0  e

     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
3  4.0   NaN  NaN
4  5.0  10.0    e

### Probem 3

In [48]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value1': [10, 20, 30, 40, 50, 60],
    'Value2': [100, 200, 300, 400, 500, 600]
})

# Basic groupby and aggregation
print("Mean of Value1 for each Category:")
print(df.groupby('Category')['Value1'].mean())

print("Max of Value2 for each Category:")
print(df.groupby('Category')['Value2'].max())

print("Sum of Value1 for each Category:")
print(df.groupby('Category')['Value1'].sum())

Mean of Value1 for each Category:
Category
A    30.0
B    40.0
Name: Value1, dtype: float64
Max of Value2 for each Category:
Category
A    500
B    600
Name: Value2, dtype: int64
Sum of Value1 for each Category:
Category
A     90
B    120
Name: Value1, dtype: int64