Email: mahfuzzayn8@gmail.com

In [635]:
# Starter Code

# You must run this code and use this dataset for all questions

import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

# 1) NumPy - 5 Questions

#### Question 01: Use  NumPy arrays, the emp_ages and emp_income. Print both arrays and display:
- data type
- number of dimensions
- shape
- total number of elements

In [636]:
data = pd.read_csv("./staff_data.csv").to_numpy()

print(data)
print(data.dtype)
print(data.shape)
print(data.size)

[[101 54 51725 'HR Manager']
 [102 23 38495 'Accountant']
 [103 20 35452 'Operations Manager']
 [104 43 82295 'Digital Marketer']
 [105 37 72187 'Backend Developer']
 [106 37 58915 'HR Manager']
 [107 21 76159 'Backend Developer']
 [108 35 92864 'Sales Executive']
 [109 24 76155 'Sales Executive']
 [110 38 90494 'HR Executive']
 [111 31 68641 'Backend Developer']
 [112 35 48079 'Marketing Executive']
 [113 29 56879 'Sales Executive']
 [114 38 83682 'Operations Manager']
 [115 27 94722 'Digital Marketer']
 [116 45 91041 'Financial Analyst']
 [117 51 48899 'Sales Executive']
 [118 48 68744 'Operations Manager']
 [119 20 63187 'Software Developer']
 [120 32 74146 'Backend Developer']
 [121 51 75641 'Sales Executive']
 [122 53 47678 'Sales Executive']
 [123 21 76760 'Accountant']
 [124 26 78354 'Software Developer']
 [125 53 60584 'HR Executive']
 [126 37 79898 'Operations Manager']
 [127 26 59682 'Digital Marketer']
 [128 21 71888 'HR Executive']
 [129 45 51086 'Software Developer']
 [130 30 73700 'Accountant']
 [131 20 82550 'Sales Executive']
 [132 47 71447 'Marketing Executive']
 [133 53 76100 'Digital Marketer']
 [134 53 72269 'Backend Developer']
 [135 23 73314 'Software Developer']
 [136 24 87428 'Software Developer']
 [137 21 94427 'Sales Executive']
 [138 30 84188 'Accountant']
 [139 27 52013 'HR Manager']
 [140 25 63326 'Sales Executive']
 [141 39 44396 'Marketing Executive']
 [142 20 59500 'Digital Marketer']
 [143 47 55523 'HR Executive']
 [144 41 58602 'Accountant']
 [145 22 90794 'HR Executive']
 [146 52 41061 'HR Manager']
 [147 42 82331 'Software Developer']
 [148 54 73048 'Software Developer']
 [149 31 59727 'Digital Marketer']
 [150 50 50398 'Marketing Executive']]
object
(50, 4)
200

#### Question 02: Using NumPy functions:
- Find the maximum and minimum salary
- Calculate the average salary
- Calculate the average age
    Print all results.

In [637]:
print(data[:,2:3].max())
print(data[:,2:3].min())
print(data[:,2:3].mean())

print(data[:,1:2].mean())

94722
35452
68409.48
35.44

### Question 03: From the emp_ages array:
Extract employees who:
are aged between 25 and 40,
 AND
Emp_salary : have salary greater than 50,000
Then : 
Print the filtered values
Count how many employees satisfy this conditio

In [638]:
employee_ages = data[:,1:2]
  
filtered_arr_age = employee_ages[(employee_ages > 25) & (employee_ages < 40)]

print(filtered_arr_age)

employee_salaries = data[:,2:3]

filtered_arr_sal = employee_salaries[employee_salaries > 50000]

print(filtered_arr_sal)
print(filtered_arr_sal.size)

[37 37 35 38 31 35 29 38 27 32 26 37 26 30 30 27 39 31]
[51725 82295 72187 58915 76159 92864 76155 90494 68641 56879 83682 94722
 91041 68744 63187 74146 75641 76760 78354 60584 79898 59682 71888 51086
 73700 82550 71447 76100 72269 73314 87428 94427 84188 52013 63326 59500
 55523 58602 90794 82331 73048 59727 50398]
43

#### Question 04: Create a new NumPy array where each employee’s age is adjusted based on:
Add 4 years if age is less than the average age
Add 2 years if age is greater than or equal to the average age
Do NOT modify the original array.
 
Print:
original array
updated array
average age used for condition

In [639]:
employee_ages = data[:,1:2].copy()
average_age = employee_ages.mean()

employee_ages[employee_ages < average_age] += 4
employee_ages[employee_ages >= average_age] += 2

print(data[0:10,1:2])
print(employee_ages[0:10])
print(average_age)

[[54]
 [23]
 [20]
 [43]
 [37]
 [37]
 [21]
 [35]
 [24]
 [38]]
[[56]
 [27]
 [24]
 [45]
 [39]
 [39]
 [25]
 [41]
 [28]
 [40]]
35.44

#### Question 05: Using NumPy:
Assume all salaries of Tech roles increase by 8%
Calculate the new total salary expense
Find the overall increase in expense after the raise

 Print both old and new totals along with the difference.

In [640]:
mask = (data[:,3] == "Software Developer") | (data[:,3] == "Digital Marketer") | (data[:,3] == "Backend Developer")

filtered_data = data.copy()
filtered_data[mask, 2] += filtered_data[mask, 2] * 0.08

prev_salary_expense = data[:,2:3].sum()
new_salary_expense = filtered_data[:,2:3].sum()

print(f"Previous: {prev_salary_expense}")
print(f"New: {new_salary_expense:0.0f}")
print(f"Difference: {new_salary_expense - prev_salary_expense:0.0f}")

Previous: 3420474
New: 3524808
Difference: 104334

# 2) Pandas - 5 Questions

#### Question 06: Load the staff_data.csv file into a Pandas DataFrame.
Display the first 3 rows
Show dataset information using .info()
Display summary statistics using .describe()

In [641]:
df = pd.read_csv("./staff_data.csv")

df.head(3)

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager

In [642]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     str
dtypes: int64(3), str(1)
memory usage: 1.7 KB

In [643]:
df.describe()

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

#### Question 07: Filter the dataset to include only:
emp_id, emp_age, role
Then:
Select employees whose age is between 25 and 40
Sort them by emp_id
Display the last 3 rows of the result

In [644]:
df.drop('emp_salary', axis="columns", inplace=True)

df

    emp_id  emp_age                 role
0      101       54           HR Manager
1      102       23           Accountant
2      103       20   Operations Manager
3      104       43     Digital Marketer
4      105       37    Backend Developer
5      106       37           HR Manager
6      107       21    Backend Developer
7      108       35      Sales Executive
8      109       24      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
15     116       45    Financial Analyst
16     117       51      Sales Executive
17     118       48   Operations Manager
18     119       20   Software Developer
19     120       32    Backend Developer
20     121       51      Sales Executive
21     122       53      Sales Executive
22     123       21           Accountant
23     124       26   Software Developer
24     125       53         HR Executive
25     126       37   Operations Manager
26     127       26     Digital Marketer
27     128       21         HR Executive
28     129       45   Software Developer
29     130       30           Accountant
30     131       20      Sales Executive
31     132       47  Marketing Executive
32     133       53     Digital Marketer
33     134       53    Backend Developer
34     135       23   Software Developer
35     136       24   Software Developer
36     137       21      Sales Executive
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
41     142       20     Digital Marketer
42     143       47         HR Executive
43     144       41           Accountant
44     145       22         HR Executive
45     146       52           HR Manager
46     147       42   Software Developer
47     148       54   Software Developer
48     149       31     Digital Marketer
49     150       50  Marketing Executive

In [645]:
df = df[(df['emp_age'] > 25) & (df['emp_age'] < 40)].sort_values("emp_id", ascending=True).tail(3)

df

    emp_id  emp_age                 role
38     139       27           HR Manager
40     141       39  Marketing Executive
48     149       31     Digital Marketer

#### Question 08: Filter the DataFrame to show only employees working in the "HR" role.
Print the filtered data
Show the total number of HR employees

In [646]:
df = pd.read_csv("./staff_data.csv")

df = df[(df['role'] == "HR Manager") | (df['role'] == "HR Executive")]

print(f"Total Employees: {df['role'].count()}")

Total Employees: 9

#### Question 09: Sort the DataFrame by:
emp_age (ascending)
and then by emp_salary (descending)
Display the top 5 employees after sorting, including:
emp_id
role
emp_salary

In [647]:
df = pd.read_csv("./staff_data.csv")

df.sort_values(['emp_age', 'emp_salary'], ascending=[1, 0])

df.drop('emp_age', axis="columns", inplace=True)

df.head(5)

   emp_id  emp_salary                role
0     101       51725          HR Manager
1     102       38495          Accountant
2     103       35452  Operations Manager
3     104       82295    Digital Marketer
4     105       72187   Backend Developer

#### Question 10: Using .loc:
Increase salary by 12% for "Software Developer" and "Backend Developer"
Increase salary by 5% for all other roles
Then:
Print the dataframe that includes role , previous_salary , new_salary , increase_of_salary

In [648]:
df = pd.read_csv("./staff_data.csv")

mask = (df['role'].isin(["Software Developer", "Backend Developer"]))
previous_salary = df['emp_salary']
roles = df['role']
result = pd.DataFrame()

result['role'] = roles
result['previous_salary'] = previous_salary
result['new_salary'] = np.where(mask, previous_salary + previous_salary * 0.12, previous_salary + previous_salary * 0.05)
result["increase_of_salary"] = np.where(mask, 12, 5) 

result

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725    54311.25                   5
1            Accountant            38495    40419.75                   5
2    Operations Manager            35452    37224.60                   5
3      Digital Marketer            82295    86409.75                   5
4     Backend Developer            72187    80849.44                  12
5            HR Manager            58915    61860.75                   5
6     Backend Developer            76159    85298.08                  12
7       Sales Executive            92864    97507.20                   5
8       Sales Executive            76155    79962.75                   5
9          HR Executive            90494    95018.70                   5
10    Backend Developer            68641    76877.92                  12
11  Marketing Executive            48079    50482.95                   5
12      Sales Executive            56879    59722.95                   5
13   Operations Manager            83682    87866.10                   5
14     Digital Marketer            94722    99458.10                   5
15    Financial Analyst            91041    95593.05                   5
16      Sales Executive            48899    51343.95                   5
17   Operations Manager            68744    72181.20                   5
18   Software Developer            63187    70769.44                  12
19    Backend Developer            74146    83043.52                  12
20      Sales Executive            75641    79423.05                   5
21      Sales Executive            47678    50061.90                   5
22           Accountant            76760    80598.00                   5
23   Software Developer            78354    87756.48                  12
24         HR Executive            60584    63613.20                   5
25   Operations Manager            79898    83892.90                   5
26     Digital Marketer            59682    62666.10                   5
27         HR Executive            71888    75482.40                   5
28   Software Developer            51086    57216.32                  12
29           Accountant            73700    77385.00                   5
30      Sales Executive            82550    86677.50                   5
31  Marketing Executive            71447    75019.35                   5
32     Digital Marketer            76100    79905.00                   5
33    Backend Developer            72269    80941.28                  12
34   Software Developer            73314    82111.68                  12
35   Software Developer            87428    97919.36                  12
36      Sales Executive            94427    99148.35                   5
37           Accountant            84188    88397.40                   5
38           HR Manager            52013    54613.65                   5
39      Sales Executive            63326    66492.30                   5
40  Marketing Executive            44396    46615.80                   5
41     Digital Marketer            59500    62475.00                   5
42         HR Executive            55523    58299.15                   5
43           Accountant            58602    61532.10                   5
44         HR Executive            90794    95333.70                   5
45           HR Manager            41061    43114.05                   5
46   Software Developer            82331    92210.72                  12
47   Software Developer            73048    81813.76                  12
48     Digital Marketer            59727    62713.35                   5
49  Marketing Executive            50398    52917.90                   5